CREATE TABLE IF NOT EXISTS services (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  name TEXT NOT NULL,
  desc TEXT NOT NULL DEFAULT "",
  host TEXT NOT NULL, 
  path TEXT NOT NULL, 
  repo TEXT NOT NULL DEFAULT "",
  enabled BOOL NOT NULL DEFAULT 1,
  UNIQUE(host, path)
  UNIQUE(name)
);

CREATE TABLE IF NOT EXISTS admins (
  id INTEGER PRIMARY KEY AUTOINCREMENT,
  user TEXT NOT NULL,
  serial TEXT NOT NULL,
  UNIQUE(serial)
);